from . import test_agreement
from . import test_agreement_appendix
from . import test_agreement_clause
from . import test_agreement_line
from . import test_agreement_recital
from . import test_agreement_section
from . import test_create_agreement_wizard
from . import test_menu_uninstall
from . import test_models
