[project]
name = "odoo-addons-oca-agreement"
version = "17.0.20240924.0"
dependencies = [
    "odoo-addon-agreement>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
